apiVersion: v1
kind: ConfigMap
metadata:
  name: launchboard-config
  namespace: launchboard
data:
  APP_NAME: "DevOps LaunchBoard API"
  APP_ENV: "kubernetes"
  CORS_ORIGINS: "http://launchboard.local,http://localhost:8080,http://127.0.0.1:8080"
  SEED_DEMO_DATA: "true"
  POSTGRES_DB: "launchboard"
  POSTGRES_USER: "postgres"
