apiVersion: v1
kind: Secret
metadata:
  name: launchboard-secret
  namespace: launchboard
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change-me-for-class"
  DATABASE_URL: "postgresql+asyncpg://postgres:change-me-for-class@postgres:5432/launchboard"

